//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_inform
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test_informationEntities : DbContext
    {
        public Test_informationEntities()
            : base("name=Test_informationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<first_answers> first_answers { get; set; }
        public virtual DbSet<questions> questions { get; set; }
        public virtual DbSet<results> results { get; set; }
        public virtual DbSet<second_answers> second_answers { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<third_answers> third_answers { get; set; }
    }
}
